version: "3.7"

services:
  back:
    build:
      context: ./back
    command: gunicorn static_apps.wsgi --bind 0.0.0.0:8000
    # ports:
    #   - "8000:8000"
  
  front:
    build:
      context: ./front
    volumes:
      - react_build:/usr/src/build
  
  nginx:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - back
      - front

volumes:
  react_build:
